version: 2.1

parameters:
  terraform_apply:
    type: boolean
    default: false
  terraform_destroy:
    type: boolean
    default: true

orbs:
  slack: circleci/slack@4.4.4
  terraform: circleci/terraform@3.0.0

jobs:
  slack_notify:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "Start to Create or Update or Remove the EKS cluster via terraform by $CIRCLE_USERNAME",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "divider"
                }
              ]
            }
          event: always
          channel: circleci-notification
  
  terraform_init:
    docker:
      - image: hashicorp/terraform:1.0.5
    steps:
      - checkout
      - terraform/init:
          path: .
      - terraform/validate:
          path: .
      - terraform/fmt:
          path: .
      - terraform/plan:
          path: .

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.0.5
    steps:
      - checkout
      - run:
          name: install curl
          command: |
            apk --no-cache add curl
      - terraform/init:
          path: .
      - terraform/plan:
          path: .
      - terraform/apply:
          path: .

  slack_notify_action:
    machine:
      image: ubuntu-1604:202007-01
    parameters:
      terraform_action:
       description: |
          If to create to remove the cluster
       type: string
    steps:
      - slack/notify:
          custom: |
           {
              "blocks": [
                {
                  "type": "section",
                 "fields": [
                   {
                      "type": "plain_text",
                      "text": "<< parameters.terraform_action >> the EKS cluster via terraform by $CIRCLE_USERNAME has been done",
                      "emoji": true
                    }
                  ]
                },
                {
                  "type": "divider"
                }
              ]
            }
          event: always
          channel: circleci-notification

  terraform_destroy:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      - terraform/install:
          arch: amd64
          os: linux
          terraform_version: 1.0.5
      - terraform/init:
          path: .
      - terraform/plan:
          path: .
      - run:
          name: "Destruction of env"
          command: |
            terraform destroy --auto-approve -input=false
          
workflows:
  terraform_create_eks_cluster:
    when: << pipeline.parameters.terraform_apply >>
    jobs:
      - slack_notify
      - terraform_init:
          requires:
            - slack_notify
      - terraform_apply:
          requires:
            - terraform_init
          filters:
            branches:
              only: master  
      - slack_notify_action:
          terraform_action: create
          requires:
            - terraform_apply
  terraform_remove_eks_cluster:
    when: << pipeline.parameters.terraform_destroy >>  
    jobs:
      - slack_notify
      - terraform_init:
          requires:
            - slack_notify
      - terraform_destroy:
          requires:
            - terraform_init
          filters:
            branches:
              only: master  
      - slack_notify_action:
          terraform_action: create
          requires:
            - terraform_destroy        
      